import { Download } from 'lucide-react';
import InsuranceShell, {
  KpiHostedCard,
  StatusPill,
  formatCurrency,
  formatNumber,
  statusTone,
  titleCase,
  useInsurancePageData,
} from './InsuranceShell';

export const InsuranceReports = () => {
  const { data, loading, error, claimTotal, openFraud, refetch } = useInsurancePageData();
  const reports = data?.reportRuns ?? [];
  const fraudExposure = openFraud.reduce((sum, alert) => sum + alert.exposureAmountAed, 0);
  const ready = reports.filter((r) => r.status === 'ready').length;
  const running = reports.filter((r) => r.status === 'running').length;
  const failed = reports.filter((r) => r.status === 'failed').length;

  const grouped: Record<string, typeof reports> = {};
  reports.forEach((r) => {
    const lower = r.reportName.toLowerCase();
    let cat = 'Operational';
    if (lower.includes('dha') || lower.includes('regulator') || lower.includes('compliance')) cat = 'Regulatory';
    else if (lower.includes('finance') || lower.includes('claim') || lower.includes('budget')) cat = 'Financial';
    else if (lower.includes('utiliz') || lower.includes('member') || lower.includes('cohort')) cat = 'Utilization';
    else if (lower.includes('fraud') || lower.includes('risk')) cat = 'Risk & Fraud';
    grouped[cat] = grouped[cat] ?? [];
    grouped[cat].push(r);
  });

  return (
    <InsuranceShell data={data} loadError={error ?? null} onRetry={() => void refetch()}>
      <section className="grid grid-cols-2 gap-3 sm:grid-cols-4">
        <KpiHostedCard label="Total Reports" value={loading ? '...' : formatNumber(reports.length)} caption="Across all categories" tone="blue" />
        <KpiHostedCard label="Ready to Download" value={loading ? '...' : formatNumber(ready)} caption={`${running} running · ${failed} failed`} tone="emerald" />
        <KpiHostedCard label="Claims Value" value={loading ? '...' : formatCurrency(claimTotal)} caption="Current period" tone="violet" />
        <KpiHostedCard label="Fraud Exposure" value={loading ? '...' : formatCurrency(fraudExposure)} caption="Open investigations" tone="red" />
      </section>

      <div className="space-y-5">
        {Object.entries(grouped).map(([category, items]) => (
          <article key={category} className="rounded-2xl border border-slate-200 bg-white shadow-sm">
            <div className="flex items-start justify-between gap-3 border-b border-slate-100 px-5 py-4">
              <div>
                <h2 className="text-[15px] font-bold text-slate-900">{category} Reports</h2>
                <p className="mt-0.5 text-xs text-slate-400">
                  {items.length} report{items.length === 1 ? '' : 's'} in this category
                </p>
              </div>
            </div>
            <div className="divide-y divide-slate-100">
              {items.map((report) => (
                <div key={report.id} className="flex items-center justify-between gap-4 px-5 py-3">
                  <div>
                    <div className="text-sm font-semibold text-slate-900">{report.reportName}</div>
                    <div className="text-xs text-slate-400">
                      <StatusPill tone={statusTone(report.status)}>{titleCase(report.status)}</StatusPill>
                      <span className="ml-2">{report.periodLabel}</span>
                    </div>
                  </div>
                  <button
                    type="button"
                    onClick={() => {
                      const lines = [
                        report.reportName,
                        `Status: ${report.status}`,
                        `Period: ${report.periodLabel}`,
                        '',
                        `Generated by CeenAiX insurance portal · ${new Date().toLocaleString()}`,
                      ];
                      const blob = new Blob([lines.join('\n')], { type: 'text/plain;charset=utf-8' });
                      const url = URL.createObjectURL(blob);
                      const link = document.createElement('a');
                      link.href = url;
                      link.download = `${report.reportName.toLowerCase().replace(/[^a-z0-9]+/g, '-')}-${new Date().toISOString().slice(0, 10)}.txt`;
                      document.body.appendChild(link);
                      link.click();
                      document.body.removeChild(link);
                      URL.revokeObjectURL(url);
                    }}
                    disabled={report.status !== 'ready'}
                    className="inline-flex items-center gap-1.5 rounded-lg bg-[#1E3A5F] px-3 py-1.5 text-xs font-bold text-white hover:bg-[#27537f] disabled:cursor-not-allowed disabled:bg-slate-300"
                  >
                    <Download className="h-3.5 w-3.5" /> Download
                  </button>
                </div>
              ))}
            </div>
          </article>
        ))}
        {reports.length === 0 ? (
          <div className="rounded-2xl border border-dashed border-slate-200 bg-white p-6 text-center text-sm text-slate-500">
            No report runs available yet.
          </div>
        ) : null}
      </div>
    </InsuranceShell>
  );
};

export default InsuranceReports;